config/routes.rb
Farmhouse::Application.routes.draw do
  # REDIRECTS...

  # conf by year redirects to conf by id
  match "/2011"            => redirect("/conf/1")
  match "/2012"            => redirect("/conf/2")
  match "/2013"            => redirect("/conf/3")
  match "/conf/2011"       => redirect("/conf/1")
  match "/conf/2012"       => redirect("/conf/2")
  match "/conf/2013"       => redirect("/conf/3")
  match "/conf/2011/talks" => redirect("/conf/1")
  match "/conf/2012/talks" => redirect("/conf/2")
  match "/conf/2013/talks" => redirect("/conf/3")

  # fhc1 talks
  match "/2011/talks/evan-phoenix"    => redirect("/conf/1/evan-phoenix")
  match "/2011/talks/leah-silber"     => redirect("/conf/1/leah-silber")
  match "/2011/talks/sean-bonner"     => redirect("/conf/1/sean-bonner")
  match "/2011/talks/micki-krimmel"   => redirect("/conf/1/micki-krimmel")
  match "/2011/talks/tj-nelson-jr"    => redirect("/conf/1/tj-nelson-jr")
  match "/2011/talks/sarah-mei"       => redirect("/conf/1/sarah-mei")
  match "/2011/talks/eli-duke"        => redirect("/conf/1/eli-duke")
  match "/2011/talks/meghann-millard" => redirect("/conf/1/meghann-millard")
  match "/2011/talks/suzan-bond"      => redirect("/conf/1/suzan-bond")
  match "/2011/talks/aaron-patterson" => redirect("/conf/1/aaron-patterson")

  # fhc1 talks
  match "/2012/talks/mapping-the-la-tech-scene"                                                                       => redirect("/conf/2/mapping-the-la-tech-scene")
  match "/2012/talks/the-map-from-trauma-to-survival"                                                                 => redirect("/conf/2/the-map-from-trauma-to-survival")
  match "/2012/talks/navigating-the-gender-landscape"                                                                 => redirect("/conf/2/navigating-the-gender-landscape")
  match "/2012/talks/the-map-versus-the-territory"                                                                    => redirect("/conf/2/the-map-versus-the-territory")
  match "/2012/talks/how-einstein-led-me-to-bliss--a-carnie-kingdom--and-pioneering-new-methods-in-video-mapping"     => redirect("/conf/2/how-einstein-led-me-to-bliss")
  match "/2012/talks/there-rsquo-s-no-map-for-inventiveness"                                                          => redirect("/conf/2/theres-no-map-for-inventiveness")
  match "/2012/talks/mapping-a-way-to-the-stars-by-disrupting-the-status-quo"                                         => redirect("/conf/2/mapping-a-way-to-the-stars")
  match "/2012/talks/culture-reboot--mapping-open-spaces-and-collaborative-practices-in-the-emergent-network-economy" => redirect("/conf/2/culture-reboot-mapping-open-spaces")
  match "/2012/talks/falling-off-the-map--the-skid-row-life-cycle"                                                    => redirect("/conf/2/falling-off-the-map-skid-row-life-cycle")
  match "/2012/talks/mapping-with-wit-z-"                                                                             => redirect("/conf/2/mapping-with-witz")

  # fhc3 talks
  match "/2013/talks/meme--myself--and-eye-" => redirect("/conf/3/meme-myself-and-eye")

  # fhc5 talks
  match "/conf/5/eleanor-saitta-tba" => redirect("/conf/5/the-collapse-of-trust")
  # ...REDIRECTS

  root to: "about#index"

  # homepage mailing list sign up
  resources :mailing_lists, only: [:create]

  # labs
  match "/bs"                   => redirect("/labs")
  match "/labs"                 => redirect("/labs/learn-to-code/1")
  match "/labs/learn-to-code/1" => ("labs#index")
  match "/labs/learn-to-code"   => redirect("/labs/learn-to-code/1")

  # barn talks
  match "/barn-talks"                    => redirect("/conf")
  match "/barn-talks/1"                  => redirect("/conf")
  match "/barn-talks/1-warren-ellis"     => redirect("/conf")
  match "/barn-talks/2"                  => redirect("/conf")
  match "/barn-talks/2-margaret-killjoy" => redirect("/conf")

  # about
  match "/rules"      => "about#rules",      as: "rules"
  match "/register"   => "about#register",   as: "register"
  match "/us"         => "about#us",         as: "us"
  match "/house"      => "about#house",      as: "house"
  match "/sandwiches" => "about#sandwiches", as: "sandwiches"
  match "/barn"       => "about#barn",       as: "barn"
  match "/location"   => "about#location",   as: "location"
  match "/civ"        => "about#civ",        as: "civ"

  # memberships
  match "/memberships"       => "memberships#index",     as: "memberships"
  match "/memberships/:slug" => "memberships#show",      as: "membership"

  # conf
  match "/conf/code-of-conduct" => "confs#code_of_conduct",   as: "code_of_conduct"
  match "/prospectus"           => redirect("/conf/sponsor"), as: "prospectus"
  match "/conf/sponsor"         => "confs#sponsor",           as: "sponsor"

  match "/conf"                 => redirect("/conf/5")

  match "/conf/:id"             => "confs#show",              as: "conf"
  match "/conf/:id/photos"      => "photos#index",            as: "conf_photos"
  match "/conf/:id/talks"       => "talks#index",             as: "conf_talks"
  match "/conf/:id/:slug"       => "talks#show",              as: "conf_talk"

  # ??? delete
  match "/people/:slug"    => "people#show",             as: "person_slug"

  # podcast
  match "/podcast/feed"    => "podcast#feed",            as: "podcasts_feed"
  match "/podcast"         => "podcast#index",           as: "podcasts"
  match "/podcast/sponsor" => "podcast#sponsor",         as: "podcast_sponsor"
  match "/podcast/:id"     => "podcast#show",            as: "podcast"

  # publishing
  match "/publishing"      => redirect("/publishing/1"), as: "publishing"
  match "/publishing/:id"  => "publishing#show",         as: "publication"

  # shop
  match "/shop"            => redirect("http://shop.farmhouse.co"), as: "shop"

  namespace :admin do
    resources :episodes #podcast admin
  end
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  belongs_to :conf
  has_many :speakings
  has_many :people, :through => :speakings, :uniq => true

  has_many :photos
  has_many :videos
  has_many :tweets
  has_many :links

  before_create :sluggify

  class << self
    def options_for_select
      Talk.all.map { |t| [t.title, t.id] }
    end
  end

  def sluggify
    if self.slug.blank?
      s = self.title
    else
      s = self.slug
    end

    separator = "-"
    self.slug = s.downcase.gsub(/_|\s|\W/, separator).gsub(/-{2,}/, separator).gsub(/(-)+$/, "")
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def show
    @slug  = "talk"
    conf   = Conf.find(params[:id])
    @talk  = conf.talks.where(:slug => params[:slug]).first
    @title = %Q{"#{@talk.title}" by #{@talk.people.first.name}}
  end

  def index
    redirect_to conf_path(params[:id])
  end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :conf_id %><br />
    <%= f.select :conf_id, Conf.options_for_select %>
  </div>


  <div class="field">
    <%= label_tag :person_id %><br />
    <%= select_tag :person_id, options_from_collection_for_select(Person.all, :id, :name), :include_blank => true %>
  </div>


  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.check_box :accepted %>
  </div>
  <div class="field">
    <%= f.label :keynote %><br />
    <%= f.check_box :keynote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing talk</h1>

<%= render "form" %>

<p>
  <%= link_to "Show", @talk %>
  <%= link_to "Back", talks_path %>
</p>

app/views/talks/index.html.erb
<h1>
  Talks
  ( <%= link_to "New", new_talk_path %> )
</h1>

<table>
  <tr>
    <th>Conf</th>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Description</th>
    <th>Accepted</th>
    <th>Keynote</th>
    <th></th>
  </tr>

  <% @talks.each do |talk| %>
    <tr>
      <td><%= link_to talk.conf.name, talk.conf %></td>
      <td><%= talk.title %></td>
      <td><%= talk.subtitle %></td>
      <td><%= talk.description %></td>
      <td><%= talk.accepted %></td>
      <td><%= talk.keynote %></td>
      <td>
        <%= link_to "Show", talk %>
        <%= link_to "Edit", edit_talk_path(talk) %>
        <%= link_to "Destroy", talk, :confirm => "Are you sure?", :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/talks/new.html.erb
<h1>New Talk</h1>

<%= render "form" %>

<%= link_to "Back", talks_path %>

app/views/talks/show.html.erb
<%= render "/confs/nav" %>

<article class="vevent h-event">
  <header>
    <h1 class="p-name summary"><%= @talk.title.html_safe %></h1>

    <h2>
      By <span class="h-card vcard"><span class="p-name fn n"><%= @talk.people.first.name %></span></span>
      at <%= link_to @talk.conf.name, @talk.conf, :class => "u-url url p-location location" %>
    </h2>
  </header>


  <div class="row">
    <div class="span6">
      <%= remote_image_tag("speakers/#{@talk.people.first.slug}", :alt => @talk.people.first.name, :class => "u-photo photo") %>

      <div class="p-note note">
        <%= simple_format @talk.description.html_safe %>
      </div> <!-- .note -->

      <div class="p-note note">
        <%= @talk.people.first.bio.html_safe %>
      </div>
    </div>

    <div class="span6">
      <% unless @talk.videos.blank? %>
        <% @talk.videos.each do |video| %>

          <div class="video">

            <% if video.youtube =~ /vimeo/ %>
              <iframe height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen src="https://player.vimeo.com/video/<%= video.youtube.split("/").last %>?byline=0&amp;portrait=0"></iframe>
            <% elsif video.youtube %>
              <iframe height="360" src="http://www.youtube.com/embed/<%= video.youtube %>"></iframe>
            <% else %>
              <video controls poster="<%= video.poster_frame_url %>" preload="none">
                <source src="<%= video.mp4 %>" />
              </video>
            <% end %>

            <p class="notes">
              Video by <%= video.videographer %>.
              <%= link_to "Higher resolutions", video.canonical_url, :rel => "external" %>
              available at
              <%= link_to "Confreaks.", "http://confreaks.com", :rel => "external" %>
            </p>

          </div> <!-- .video -->

        <% end %>
      <% end %>
    </div>
  </div> <!-- .row -->
</article>