config/routes.rb
Farmhouse::Application.routes.draw do
  # REDIRECTS...

  # conf by year redirects to conf by id
  match "/2011"            => redirect("/conf/1")
  match "/2012"            => redirect("/conf/2")
  match "/2013"            => redirect("/conf/3")
  match "/conf/2011"       => redirect("/conf/1")
  match "/conf/2012"       => redirect("/conf/2")
  match "/conf/2013"       => redirect("/conf/3")
  match "/conf/2011/talks" => redirect("/conf/1")
  match "/conf/2012/talks" => redirect("/conf/2")
  match "/conf/2013/talks" => redirect("/conf/3")

  # fhc1 talks
  match "/2011/talks/evan-phoenix"    => redirect("/conf/1/evan-phoenix")
  match "/2011/talks/leah-silber"     => redirect("/conf/1/leah-silber")
  match "/2011/talks/sean-bonner"     => redirect("/conf/1/sean-bonner")
  match "/2011/talks/micki-krimmel"   => redirect("/conf/1/micki-krimmel")
  match "/2011/talks/tj-nelson-jr"    => redirect("/conf/1/tj-nelson-jr")
  match "/2011/talks/sarah-mei"       => redirect("/conf/1/sarah-mei")
  match "/2011/talks/eli-duke"        => redirect("/conf/1/eli-duke")
  match "/2011/talks/meghann-millard" => redirect("/conf/1/meghann-millard")
  match "/2011/talks/suzan-bond"      => redirect("/conf/1/suzan-bond")
  match "/2011/talks/aaron-patterson" => redirect("/conf/1/aaron-patterson")

  # fhc1 talks
  match "/2012/talks/mapping-the-la-tech-scene"                                                                       => redirect("/conf/2/mapping-the-la-tech-scene")
  match "/2012/talks/the-map-from-trauma-to-survival"                                                                 => redirect("/conf/2/the-map-from-trauma-to-survival")
  match "/2012/talks/navigating-the-gender-landscape"                                                                 => redirect("/conf/2/navigating-the-gender-landscape")
  match "/2012/talks/the-map-versus-the-territory"                                                                    => redirect("/conf/2/the-map-versus-the-territory")
  match "/2012/talks/how-einstein-led-me-to-bliss--a-carnie-kingdom--and-pioneering-new-methods-in-video-mapping"     => redirect("/conf/2/how-einstein-led-me-to-bliss")
  match "/2012/talks/there-rsquo-s-no-map-for-inventiveness"                                                          => redirect("/conf/2/theres-no-map-for-inventiveness")
  match "/2012/talks/mapping-a-way-to-the-stars-by-disrupting-the-status-quo"                                         => redirect("/conf/2/mapping-a-way-to-the-stars")
  match "/2012/talks/culture-reboot--mapping-open-spaces-and-collaborative-practices-in-the-emergent-network-economy" => redirect("/conf/2/culture-reboot-mapping-open-spaces")
  match "/2012/talks/falling-off-the-map--the-skid-row-life-cycle"                                                    => redirect("/conf/2/falling-off-the-map-skid-row-life-cycle")
  match "/2012/talks/mapping-with-wit-z-"                                                                             => redirect("/conf/2/mapping-with-witz")

  # fhc3 talks
  match "/2013/talks/meme--myself--and-eye-" => redirect("/conf/3/meme-myself-and-eye")

  # fhc5 talks
  match "/conf/5/eleanor-saitta-tba" => redirect("/conf/5/the-collapse-of-trust")
  # ...REDIRECTS

  root to: "about#index"

  # homepage mailing list sign up
  resources :mailing_lists, only: [:create]

  # labs
  match "/bs"                   => redirect("/labs")
  match "/labs"                 => redirect("/labs/learn-to-code/1")
  match "/labs/learn-to-code/1" => ("labs#index")
  match "/labs/learn-to-code"   => redirect("/labs/learn-to-code/1")

  # barn talks
  match "/barn-talks"                    => redirect("/conf")
  match "/barn-talks/1"                  => redirect("/conf")
  match "/barn-talks/1-warren-ellis"     => redirect("/conf")
  match "/barn-talks/2"                  => redirect("/conf")
  match "/barn-talks/2-margaret-killjoy" => redirect("/conf")

  # about
  match "/rules"      => "about#rules",      as: "rules"
  match "/register"   => "about#register",   as: "register"
  match "/us"         => "about#us",         as: "us"
  match "/house"      => "about#house",      as: "house"
  match "/sandwiches" => "about#sandwiches", as: "sandwiches"
  match "/barn"       => "about#barn",       as: "barn"
  match "/location"   => "about#location",   as: "location"
  match "/civ"        => "about#civ",        as: "civ"

  # memberships
  match "/memberships"       => "memberships#index",     as: "memberships"
  match "/memberships/:slug" => "memberships#show",      as: "membership"

  # conf
  match "/conf/code-of-conduct" => "confs#code_of_conduct",   as: "code_of_conduct"
  match "/prospectus"           => redirect("/conf/sponsor"), as: "prospectus"
  match "/conf/sponsor"         => "confs#sponsor",           as: "sponsor"

  match "/conf"                 => redirect("/conf/5")

  match "/conf/:id"             => "confs#show",              as: "conf"
  match "/conf/:id/photos"      => "photos#index",            as: "conf_photos"
  match "/conf/:id/talks"       => "talks#index",             as: "conf_talks"
  match "/conf/:id/:slug"       => "talks#show",              as: "conf_talk"

  # ??? delete
  match "/people/:slug"    => "people#show",             as: "person_slug"

  # podcast
  match "/podcast/feed"    => "podcast#feed",            as: "podcasts_feed"
  match "/podcast"         => "podcast#index",           as: "podcasts"
  match "/podcast/sponsor" => "podcast#sponsor",         as: "podcast_sponsor"
  match "/podcast/:id"     => "podcast#show",            as: "podcast"

  # publishing
  match "/publishing"      => redirect("/publishing/1"), as: "publishing"
  match "/publishing/:id"  => "publishing#show",         as: "publication"

  # shop
  match "/shop"            => redirect("http://shop.farmhouse.co"), as: "shop"

  namespace :admin do
    resources :episodes #podcast admin
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :conf
  belongs_to :talk
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
  end

  def new
    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
  end

  def create
    @video = Video.new(params[:video])

    if @video.save
      redirect_to @video, :notice => 'Video was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @video = Video.find(params[:id])

    if @video.update_attributes(params[:video])
      redirect_to @video, :notice => 'Video was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_path
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conf_id %><br />
    <%= f.select :conf_id, Conf.options_for_select %>
  </div>
  <div class="field">
    <%= f.label :talk_id %><br />
    <%= f.select :talk_id, Talk.options_for_select %>
  </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_area :caption %>
  </div>
  <div class="field">
    <%= f.label :videographer %><br />
    <%= f.text_field :videographer %>
  </div>
  <div class="field">
    <%= f.label :ogv %><br />
    <%= f.text_field :ogv %>
  </div>
  <div class="field">
    <%= f.label :mp4 %><br />
    <%= f.text_field :mp4 %>
  </div>
  <div class="field">
    <%= f.label :canonical_url %><br />
    <%= f.text_field :canonical_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>Conf</th>
    <th>Talk</th>
    <th>Caption</th>
    <th>Videographer</th>
    <th>Ogv</th>
    <th>Mp4</th>
    <th>Canonical url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.conf_id %></td>
    <td><%= video.talk_id %></td>
    <td><%= video.caption %></td>
    <td><%= video.videographer %></td>
    <td><%= video.ogv %></td>
    <td><%= video.mp4 %></td>
    <td><%= video.canonical_url %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Conf:</b>
  <%= @video.conf.name %>
</p>

<p>
  <b>Talk:</b>
  <%= @video.talk.title %>
</p>

<p>
  <b>Caption:</b>
  <%= @video.caption %>
</p>

<p>
  <b>Videographer:</b>
  <%= @video.videographer %>
</p>

<p>
  <b>OGV:</b>
  <%= @video.ogv %>
</p>

<p>
  <b>MP4:</b>
  <%= @video.mp4 %>
</p>

<p>
  <b>Canonical URL:</b>
  <%= link_to @video.canonical_url, @video.canonical_url %>
</p>

<p>
  <%= link_to 'Edit', edit_video_path(@video) %>
  <%= link_to 'Back', videos_path %>
</p>