config/routes.rb
Farmhouse::Application.routes.draw do
  # REDIRECTS...

  # conf by year redirects to conf by id
  match "/2011"            => redirect("/conf/1")
  match "/2012"            => redirect("/conf/2")
  match "/2013"            => redirect("/conf/3")
  match "/conf/2011"       => redirect("/conf/1")
  match "/conf/2012"       => redirect("/conf/2")
  match "/conf/2013"       => redirect("/conf/3")
  match "/conf/2011/talks" => redirect("/conf/1")
  match "/conf/2012/talks" => redirect("/conf/2")
  match "/conf/2013/talks" => redirect("/conf/3")

  # fhc1 talks
  match "/2011/talks/evan-phoenix"    => redirect("/conf/1/evan-phoenix")
  match "/2011/talks/leah-silber"     => redirect("/conf/1/leah-silber")
  match "/2011/talks/sean-bonner"     => redirect("/conf/1/sean-bonner")
  match "/2011/talks/micki-krimmel"   => redirect("/conf/1/micki-krimmel")
  match "/2011/talks/tj-nelson-jr"    => redirect("/conf/1/tj-nelson-jr")
  match "/2011/talks/sarah-mei"       => redirect("/conf/1/sarah-mei")
  match "/2011/talks/eli-duke"        => redirect("/conf/1/eli-duke")
  match "/2011/talks/meghann-millard" => redirect("/conf/1/meghann-millard")
  match "/2011/talks/suzan-bond"      => redirect("/conf/1/suzan-bond")
  match "/2011/talks/aaron-patterson" => redirect("/conf/1/aaron-patterson")

  # fhc1 talks
  match "/2012/talks/mapping-the-la-tech-scene"                                                                       => redirect("/conf/2/mapping-the-la-tech-scene")
  match "/2012/talks/the-map-from-trauma-to-survival"                                                                 => redirect("/conf/2/the-map-from-trauma-to-survival")
  match "/2012/talks/navigating-the-gender-landscape"                                                                 => redirect("/conf/2/navigating-the-gender-landscape")
  match "/2012/talks/the-map-versus-the-territory"                                                                    => redirect("/conf/2/the-map-versus-the-territory")
  match "/2012/talks/how-einstein-led-me-to-bliss--a-carnie-kingdom--and-pioneering-new-methods-in-video-mapping"     => redirect("/conf/2/how-einstein-led-me-to-bliss")
  match "/2012/talks/there-rsquo-s-no-map-for-inventiveness"                                                          => redirect("/conf/2/theres-no-map-for-inventiveness")
  match "/2012/talks/mapping-a-way-to-the-stars-by-disrupting-the-status-quo"                                         => redirect("/conf/2/mapping-a-way-to-the-stars")
  match "/2012/talks/culture-reboot--mapping-open-spaces-and-collaborative-practices-in-the-emergent-network-economy" => redirect("/conf/2/culture-reboot-mapping-open-spaces")
  match "/2012/talks/falling-off-the-map--the-skid-row-life-cycle"                                                    => redirect("/conf/2/falling-off-the-map-skid-row-life-cycle")
  match "/2012/talks/mapping-with-wit-z-"                                                                             => redirect("/conf/2/mapping-with-witz")

  # fhc3 talks
  match "/2013/talks/meme--myself--and-eye-" => redirect("/conf/3/meme-myself-and-eye")

  # fhc5 talks
  match "/conf/5/eleanor-saitta-tba" => redirect("/conf/5/the-collapse-of-trust")
  # ...REDIRECTS

  root to: "about#index"

  # homepage mailing list sign up
  resources :mailing_lists, only: [:create]

  # labs
  match "/bs"                   => redirect("/labs")
  match "/labs"                 => redirect("/labs/learn-to-code/1")
  match "/labs/learn-to-code/1" => ("labs#index")
  match "/labs/learn-to-code"   => redirect("/labs/learn-to-code/1")

  # barn talks
  match "/barn-talks"                    => redirect("/conf")
  match "/barn-talks/1"                  => redirect("/conf")
  match "/barn-talks/1-warren-ellis"     => redirect("/conf")
  match "/barn-talks/2"                  => redirect("/conf")
  match "/barn-talks/2-margaret-killjoy" => redirect("/conf")

  # about
  match "/rules"      => "about#rules",      as: "rules"
  match "/register"   => "about#register",   as: "register"
  match "/us"         => "about#us",         as: "us"
  match "/house"      => "about#house",      as: "house"
  match "/sandwiches" => "about#sandwiches", as: "sandwiches"
  match "/barn"       => "about#barn",       as: "barn"
  match "/location"   => "about#location",   as: "location"
  match "/civ"        => "about#civ",        as: "civ"

  # memberships
  match "/memberships"       => "memberships#index",     as: "memberships"
  match "/memberships/:slug" => "memberships#show",      as: "membership"

  # conf
  match "/conf/code-of-conduct" => "confs#code_of_conduct",   as: "code_of_conduct"
  match "/prospectus"           => redirect("/conf/sponsor"), as: "prospectus"
  match "/conf/sponsor"         => "confs#sponsor",           as: "sponsor"

  match "/conf"                 => redirect("/conf/5")

  match "/conf/:id"             => "confs#show",              as: "conf"
  match "/conf/:id/photos"      => "photos#index",            as: "conf_photos"
  match "/conf/:id/talks"       => "talks#index",             as: "conf_talks"
  match "/conf/:id/:slug"       => "talks#show",              as: "conf_talk"

  # ??? delete
  match "/people/:slug"    => "people#show",             as: "person_slug"

  # podcast
  match "/podcast/feed"    => "podcast#feed",            as: "podcasts_feed"
  match "/podcast"         => "podcast#index",           as: "podcasts"
  match "/podcast/sponsor" => "podcast#sponsor",         as: "podcast_sponsor"
  match "/podcast/:id"     => "podcast#show",            as: "podcast"

  # publishing
  match "/publishing"      => redirect("/publishing/1"), as: "publishing"
  match "/publishing/:id"  => "publishing#show",         as: "publication"

  # shop
  match "/shop"            => redirect("http://shop.farmhouse.co"), as: "shop"

  namespace :admin do
    resources :episodes #podcast admin
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @slug = "home"
    @mailing_list = MailingList.new
    render layout: false
  end

  def house
    @slug  = "house"
    @title = "A Very Brief and Incomplete History"
  end

  def rules
    @slug  = "rules"
    @title = "Rules"
  end

  def us
    @slug  = "us"
    @title = "Friends and Family"
  end

  def civ
    @slug  = "civ"
    @title = "Civ needs your help."
  end

  def register
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/_civ_progress_dollars.html.erb
4910

app/views/about/_civ_progress_percent.html.erb
<%= render("civ_progress_dollars").to_i / 20000.0 * 100 %>

app/views/about/_photo_by_ignacio_galvez.html.erb
<div class="row">
  <div class="span6">
    <%= image_tag "http://farmhouse.s3.amazonaws.com/images/location/by-ignacio-galvez/photo-by-ignacio-galvez-at-the-farmhouse-#{first}.jpg" %>

    <p>
      Photo by
      <%= link_to "Ignacio Galvez", "http://ignaciogalvez.com", :rel => "external" %>
    </p>
  </div> <!-- .span6 -->
  <div class="span6">
    <%= image_tag "http://farmhouse.s3.amazonaws.com/images/location/by-ignacio-galvez/photo-by-ignacio-galvez-at-the-farmhouse-#{second}.jpg" %>

    <p>
      Photo by
      <%= link_to "Ignacio Galvez", "http://ignaciogalvez.com", :rel => "external" %>
    </p>
  </div> <!-- .span6 -->
</div> <!-- .row -->

app/views/about/barn.html.erb
<article id="barn">

  <div class="hero-unit alert alert-info">
    <h1>The Barn</h1>
    <h2>A Hackersapce in Hollywood, CA</h2>
    <p>
      Coming soon&hellip;
    </p>
  </div>

</article>

app/views/about/civ.html.erb
<article>
  <div class="row">
    <div class="span12" id="civ">
      <h2>Meet Civ.</h2>
      <%= link_to image_tag("http://farmhouse.s3.amazonaws.com/images/people/civ.jpg", :class => "photo"), "http://twitter.com/civthedog", :title => "@CivTheDog on Twitter", :rel => "external" %><%= link_to image_tag("http://farmhouse.s3.amazonaws.com/images/people/civ-next-to-chair-wheels-by-shane-becker.jpg", :class => "photo"), "http://twitter.com/civthedog", :title => "@CivTheDog on Twitter", :rel => "external" %><%= link_to image_tag("http://farmhouse.s3.amazonaws.com/images/people/civ-next-to-closet-door-by-shane-becker.jpg", :class => "photo"), "http://twitter.com/civthedog", :title => "@CivTheDog on Twitter", :rel => "external" %><%= link_to image_tag("http://farmhouse.s3.amazonaws.com/images/people/civ-next-to-steve-klabnik-by-shane-becker.jpg", :class => "photo"), "http://twitter.com/civthedog", :title => "@CivTheDog on Twitter", :rel => "external" %>

      <p>
        It&rsquo;s
        <%= link_to "Civ&rsquo;s".html_safe, "http://twitter.com/civthedog", :title => "@CivTheDog on Twitter", :rel => "external" %>
        world. We just live in it. She likes to sleep close to things and makes
        <%= link_to "a great co-pilot.", "http://flickr.com/veganstraightedge/5408991746", :title => "(or 'pilot' in her mind)", :rel => "external" %>
      </p>

      <p>She is an almost 14 year old <a href="http://en.wikipedia.org/wiki/Entlebucher_Mountain_Dog" title="Entlebucher Mountain Dog - Wikipedia">Entlebucher Mountain Dog</a> who thinks she is still a puppy. She hasn&rsquo;t let her dodgy, distinguished old-lady hips stop her from following me up and down the stairs and all around The Farmhouse backyard.</p>

      <p>She&rsquo;s been my best buddy for almost 14 and a half years, since I rescued her in Bloomington, Indiana  when she was 6 weeks old. Together we&rsquo;ve gone on countless hikes, played infinite games of catch, lived in 8 cities, and crossed state-lines/time-zones. She hates getting groomed and will wedge herself under beds or in a cactus patch when she hears the mobile groomer&rsquo;s truck turns onto the street.</p>

      <%= image_tag("http://farmhouse.s3.amazonaws.com/images/civ/civ-from-instagram-1.jpg", :class => "photo") %><%= image_tag("http://farmhouse.s3.amazonaws.com/images/civ/civ-from-instagram-2.jpg", :class => "photo") %><%= image_tag("http://farmhouse.s3.amazonaws.com/images/civ/civ-from-instagram-3.jpg", :class => "photo") %><%= image_tag("http://farmhouse.s3.amazonaws.com/images/civ/civ-from-instagram-4.jpg", :class => "photo") %>

      <%= image_tag("http://farmhouse.s3.amazonaws.com/images/civ/civ-from-instagram-5.jpg", :class => "photo") %><%= image_tag("http://farmhouse.s3.amazonaws.com/images/civ/civ-from-instagram-6.jpg", :class => "photo") %><%= image_tag("http://farmhouse.s3.amazonaws.com/images/civ/civ-from-instagram-7.jpg", :class => "photo") %><%= image_tag("http://farmhouse.s3.amazonaws.com/images/civ/civ-from-instagram-8.jpg", :class => "photo") %>
    </div>
  </div> <!-- .row -->
</article>

app/views/about/house.html.erb
<article>
  <div class="row">
    <div class="span12">
      <%= image_tag "http://farmhouse.s3.amazonaws.com/images/home/farmhouse-sky-by-tj-nelson-jr.jpg", :alt => "Farmhouse and Sky by Tj Nelson" %>

      <p class="photo-attribution">
        <%= link_to "by", "http://flickr.com/tjnelsonjunior/5694945598", :rel => "external" %>
        <%= link_to "Tj Nelson Jr", "http://twitter.com/tjnelsonjr",     :rel => "external" %>
      </p>

      <h1>A Very Brief and Incomplete History of The Farmhouse</h1>

      <div class="row">
        <p class="span6 notes">
          The Farmhouse was built in 1903 before Hollywood was <i>Hollywood</i>.
          It sat on 300 acres of avocado grove.
          What remains is the house, some small sliver of the once massive lot
          (albeit still a very good sized yard)
          and one massive 100+ year old avocado tree in the backyard.
          Also, in the backyard are meyer lemon, nectarine and guava trees.
        </p>

        <p class="span6 notes">
          After a laundry list of owners and tenants,
          Shane moved in and turned this place into The Farmhouse,
          a place that's more than just a home.
          Currently 3 humans animals, 2 cats and 2 dogs are #occupying The Farmhouse.
          The house, yard and driveway are available to rent as a photography/film/video location.
          <a href="mailto:barn@farmhouse.co">Email</a> if you're interested.
        </p>
      </div>

    </div>
  </div>
</article>

app/views/about/index.html.erb
<!DOCTYPE html>

<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="author"      content="Shane Becker" />
  <meta name="description" content="The Farmhouse in Hollywood, California" />
  <meta name="viewport"    content="width=device-width, initial-scale=1" />

  <title>The Farmhouse in Hollywood, California</title>

  <%= stylesheet_link_tag "new/application" %>
  <%= javascript_include_tag "new/vendor/modernizr.custom.34215.js" %>
</head>

<body>
  <header role="banner">
    <div class="l-container">

      <a class="brand-logo" href="/">The Farmhouse</a>

      <div class="nav-wrapper">
        <nav class="nav-collapse" role="navigation">
          <ul class="nav-main">
            <%= nav_to "Publishing",     publishing_path %>
            <%#= nav_to "Barn Talks",     barn_talks_path %>
            <%= nav_to "Farmhouse Conf", conf_path(5) %>
            <%= nav_to "History",        house_path %>

            <%#
            <li><a href="#projects">Projects</a></li>
            <li><a href="#blog">Blog</a></li>
            <li><a href="#photos">Photos</a></li>
            <li><a href="#contact">Contact</a></li>
            %>
          </ul>
        </nav>

      </div> <!-- end .nav-wrapper -->
    </div> <!-- end .l-container -->
  </header>

  <div class="hero" style="background-image: url(<%= asset_path "http://assets.farmhouse.co.s3.amazonaws.com/images/new/shoot-it-yourself-cover.png" %>)">

  <% if flash[:notice] %>
    <div class="alert alert-info">
      <p><%= flash[:notice] %></p>
    </div>
  <% end %>
    <div class="hero-container">
      <div class="hero-content">
        <h2>Shoot It Yourself</h2>
        <h3>Farmhouse Publishing #001</h3>
        <p>
          The first release from <strong>Farmhouse Publishing</strong> is <em>Shoot It Yourself</em> by Ignacio Galvez. 80 pages of beautiful black and white photos of bands and live music.
        </p>

        <div class="hero-footer">
          <p><a href="/publishing/1">Learn more about the book.</a></p>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-home">
    <div class="l-container">
      <div class="panel-content">
        <div class="panel-img"></div>
        <p class="t-lead">Storytelling events in a barn and under a 111 year old avocado tree. Photo zines. Vegan cookbooks. A podcast. Music, editorial and fashion photography. Organic gardens. Arts, style and design blog. Personal web publishing software. Open source organization. Watercoloring painting design assets. Positive attitude / Positive altitude.</p>
        <a class="btn btn-a"href="#">We do a lot</a>
      </div>
    </div>
  </div>

  <main role="main">
    <div class="l-container">
      <div class="feature">
        <%= image_tag "http://assets.farmhouse.co.s3.amazonaws.com/images/new/farmhouse-conf-frontyard-sign-by-tj-nelson.jpg" %>
        <h3>What’s the farmhouse, anyway?</h3>
        <p>The Farmhouse is located in the heart of Hollywood, California and is home to <%= link_to "Farmhouse Publishing", publishing_path %> and (formerly) <%= "Farmhouse Conf" %>. The Farmhouse and The <%= link_to "Friends of the Farmhouse", us_path %> collaborate together or produce separately a slew of projects.</p>
      </div>
      <div class="feature">
        <%= link_to civ_path do %>
          <%= image_tag "http://assets.farmhouse.co/images/new/barn.jpg" %>
          <h3>Civ The Dog</h3>
        <% end %>
        <p><%= link_to "Civ", civ_path %> is 13 and a half years old. She&rsquo;s battling two cancers (chest and liver). We&rsquo;ve been running a fund-raiser to help defeat her medical bills and get her past this. Fortunately, a lot of people have been very generous and supportive. My undying thanks to everyone that has contributed. It&rsquo;s Civ&rsquo;s house, I just live here. &mdash; Shane</p>
      </div>
      <div class="feature">
        <%= link_to conf_path(5) do %>
          <%= image_tag "http://assets.farmhouse.co.s3.amazonaws.com/images/new/conf-5.jpg" %>
          <h3>Farmhouse Conf</h3>
        <% end %>
        <p>Farmhouse Conf was the greatest backyard storytelling conference there ever was. Nestled underneath a 111 year old avocado tree and in a <em>charming</em> old barn, FHC was sometimes described as somewhere in between Ted Talks, This American Life and a Fourth of July BBQ. <a href="/conf/5">FHC5</a> was the final show.</p>
      </div>
    </div>
  </main>

  <footer role="contentinfo">
    <div class="l-container">

      <div class="h-card">
        <div class="footer-find-us">
          <h4>Find Us</h4>
          <p class="h-adr p-adr">
            <span class="p-street-address">1558 Gordon Street</span>
            <span class="p-locality">Los Angeles,</span>
            <span class="p-region">CA</span>
            <span class="p-postal-code">90028</span>
          </p>
          <p class="p-tel">(801) 898-9481</p>
        </div>
        <div class="footer-contact">
          <h4>Contact Us</h4>
          <%= mail_to "barn@farmhouse.co", "barn@farmhouse.co", class: "u-email" %>
          <%= link_to "@farmhouse",        "https://twitter.com/farmhouse", class: "u-url", rel: "me external" %>
        </div>
      </div>

      <div class="footer-mailing">
        <h4>Mailing List</h4>

        <%= form_for(@mailing_list, html: { class: "form light-form" }) do |f| %>
          <%= f.label :email, "Stay up to date on news and events" %>

          <div class="form-single-field">
            <%= f.email_field :email %>
            <%= f.submit "Go", class: "btn btn-b" %>
          </div>
        <% end %>
      </div>

      <p class="footer-copyright">
        Copyright &copy; The Farmhouse, Inc. <span class="year"><%= Time.now.year %></span>
      </p>

    </div>
  </footer>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/vendor/jquery-2.1.0.min.js"><\/script>')</script>
  <%= javascript_include_tag "new/vendor/responsive-nav.min.js" %>
  <%= javascript_include_tag "new/scripts.js" %>
</body>
</html>

app/views/about/location.html.erb
<article id="location">
  <div class="row">
    <div class="span12">
      <h2>Photography and Film Location</h2>
    </div>
  </div>

  <div class="row">
    <h3 class="span12">Fashion Photography Shoot by Ignacio Galvez</h3>

    <div class="span12">
      <%= image_tag "http://farmhouse.s3.amazonaws.com/images/location/by-ignacio-galvez/photo-by-ignacio-galvez-at-the-farmhouse-10.jpg" %>

      <p>
        Photo by
        <%= link_to "Ignacio Galvez", "http://ignaciogalvez.com", :rel => "external" %>
      </p>
    </div> <!-- .span12 -->
  </div> <!-- .row -->

  <div class="row">
    <div class="span6">
      <%= image_tag "http://farmhouse.s3.amazonaws.com/images/location/by-ignacio-galvez/photo-by-ignacio-galvez-at-the-farmhouse-06.jpg" %>

      <p>
        Photo by
        <%= link_to "Ignacio Galvez", "http://ignaciogalvez.com", :rel => "external" %>
      </p>
    </div> <!-- .span6 -->
    <div class="span6">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div> <!-- .span6 -->
  </div> <!-- .row -->

  <%= render :partial => 'photo_by_ignacio_galvez', :locals => { :first => "08", :second => "09" } %>
  <%= render :partial => 'photo_by_ignacio_galvez', :locals => { :first => "01", :second => "02" } %>
  <%= render :partial => 'photo_by_ignacio_galvez', :locals => { :first => "03", :second => "07" } %>
  <%= render :partial => 'photo_by_ignacio_galvez', :locals => { :first => "04", :second => "05" } %>

  <div class="row">
    <h3 class="span12">Music Video Shoot by Nate Cornett</h3>

    <div class="span12">
      <iframe src="http://player.vimeo.com/video/36680439?title=0&amp;byline=0&amp;portrait=0" height="400" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
      <p>
        <a href="http://vimeo.com/36680439">Kristen May - "Goodbye My Love"</a> by <a href="http://vimeo.com/cornettdp">Nate Cornett</a>
      </p>
    </div> <!-- .span12 -->
  </div> <!-- .row -->

</article>

app/views/about/rules.html.erb
<article>
  <h1>The Farmhouse Rules</h1>

  <div class="row">
    <dl class="rules span6">
      <dt>
        <b>1</b>
        VEGAN
      </dt>
      <dd>Only vegan food is allowed</dd>

      <dt>
        <b>2</b>
        DRUG FREE
      </dt>
      <dd>If you want to smoke, walk around the block, please</dd>

      <dt>
        <b>3</b>
        COMMUNAL FOOD
      </dt>
      <dd>Eat whatever food is around the house or in the trees</dd>

      <dt>
        <b>4</b>
        DOGS
      </dt>
      <dd>Let the dogs in and out of the back door only</dd>

      <dt>
        <b>5</b>
        CLEANING
      </dt>
      <dd>Clean up after yourself</dd>
    </dl>

    <dl class="rules span6">
      <dt>
        <b>6</b>
        MUSIC
      </dt>
      <dd>Share the speakers</dd>

      <dt>
        <b>7</b>
        FRIENDDA.ORG
      </dt>
      <dd>Ask before talking publicly about someone's work</dd>

      <dt>
        <b>8</b>
        LOCKS &amp; LIGHTS
      </dt>
      <dd>If you're the last one, lock up and turn off the lights</dd>

      <dt>
        <b>9</b>
        NO DRAMA
      </dt>
      <dd>Keep it positive and leave the bullshit at home</dd>

      <dt>
        <b>10</b>
        BE SUPER AWESOME
      </dt>
    </dl>
  </div>

  <div class="row">
    <div class="span12" id="chalkboard">
      <%= image_tag "http://farmhouse.s3.amazonaws.com/images/home/farmhouse-rules-chalkboard-wall-by-heather-peterson.jpg",
                    :alt => "Farmhouse Rules Chalkboard Wall by Heather Peterson" %>
    </div>
  </div>
</article>

app/views/about/sandwiches.html.erb
<article id="sandwiches">
  <div class="row">
    <div class="span12">
      <h2>Sandwiches</h2>
    </div>
  </div>

  <ul class="thumbnails row">
    <li class="span3"><span class="thumbnail"><a href="http://www.flickr.com/photos/veganstraightedge/8316505931/" title="I made this sandwich for dinner."><img src="http://farm9.staticflickr.com/8503/8316505931_de59d479d6_z.jpg" alt="I made this sandwich for dinner."></a>                                </span></li>
    <li class="span3"><span class="thumbnail"><a href="http://www.flickr.com/photos/veganstraightedge/8316509105/" title="Tonight's sandwich, open face."><img src="http://farm9.staticflickr.com/8497/8316509105_7cde020f39_o.jpg" alt="Tonight's sandwich, open face."></a>                                    </span></li>
    <li class="span3"><span class="thumbnail"><a href="http://www.flickr.com/photos/veganstraightedge/8316509323/" title="Tonight's sandwich, cut in half."><img src="http://farm9.staticflickr.com/8355/8316509323_9225373e4c_o.jpg" alt="Tonight's sandwich, cut in half."></a>                                </span></li>
    <li class="span3"><span class="thumbnail"><a href="http://www.flickr.com/photos/veganstraightedge/8316515931/" title="Today's lunch sandwich."><img src="http://farm9.staticflickr.com/8501/8316515931_c0f9374597_o.jpg" alt="Today's lunch sandwich."></a>                                                  </span></li>
    <li class="span3"><span class="thumbnail"><a href="http://www.flickr.com/photos/veganstraightedge/8316528081/" title="Lunch sandwich. English muffin. Daiya cheese..."><img src="http://farm9.staticflickr.com/8496/8316528081_056630b78d_o.jpg" alt="Lunch sandwich. English muffin. Daiya cheese..."></a>  </span></li>
    <li class="span3"><span class="thumbnail"><a href="http://www.flickr.com/photos/veganstraightedge/8316582377/" title="Vegan God Damn Quesadillas (GDQs) are..."><img src="http://farm9.staticflickr.com/8491/8316582377_a9c382bdf6_o.jpg" alt="Vegan God Damn Quesadillas (GDQs) are..."></a>                </span></li>
    <li class="span3"><span class="thumbnail"><a href="http://www.flickr.com/photos/veganstraightedge/8317637400/" title="The cooked and played God Damn..."><img src="http://farm9.staticflickr.com/8354/8317637400_278da6972a_o.jpg" alt="The cooked and played God Damn..."></a>                              </span></li>
    <li class="span3"><span class="thumbnail"><a href="http://www.flickr.com/photos/veganstraightedge/8317639032/" title="Two cheese, avocado and nooch sandwich..."><img src="http://farm9.staticflickr.com/8499/8317639032_9c6b9e8df2_o.jpg" alt="Two cheese, avocado and nooch sandwich..."></a>              </span></li>
  </ul>
</article>